services:
  - type: web
    name: lightning-studio-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x start.sh && ./start.sh
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: DATABASE_URL
        sync: false  # Set this manually if using database